namespace DeviceManager.BRICK32
{
    public enum STAR_RECEIVE_MASK
    {
        STAR_RECEIVE_PACKETS,
        STAR_RECEIVE_CHUNKS,
        STAR_RECEIVE_TIMECODES,
        STAR_RECEIVE_FCTS,
        STAR_RECEIVE_NULL,
        STAR_RECEIVE_LINK_STATE_EVENTS,
        STAR_RECEIVE_LINK_SPEED_EVENTS,
        STAR_RECEIVE_TIMESTAMP_EVENTS,
    }
}
